<?php


class RecordsMostPointsInARegularSeasonTest extends \App\Infrastructure\Test\TestCaseCore
{

    public $chrisLee;
    public $zachR;
    public $kevenB;
    public $ghislainD;
    public $paulE;
    public $paulG;
    public $davidR;
    public $chrisR;
    public $jeremieR;
    public $jacquesAuger;
    public $colinLemoine;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub


        $this->chrisLee = $this->genPlayerWithName("Chris", "Lee");
        $this->zachR = $this->genPlayerWithName("Zach", "Riet");
        $this->kevenB = $this->genPlayerWithName("Keven", "Barron");
        $this->ghislainD = $this->genPlayerWithName("Ghislain", "Druwé");
        $this->paulE = $this->genPlayerWithName("Paul", "Everton");
        $this->paulG = $this->genPlayerWithName("Paul", "Gagne");
        $this->davidR = $this->genPlayerWithName("David", "Robin");
        $this->chrisR = $this->genPlayerWithName("Chris", "Robin");
        $this->jeremieR  = $this->genPlayerWithName("Jeremie", "Robin");
        $this->jacquesAuger = $this->genPlayerWithName("Jacques", "Auger");
        $this->colinLemoine = $this->genPlayerWithName("Colin", "Lemoine");
    }

    public function test_record()
    {
        $this->generateMultipleGamesForAGivenSeason(1, 1);

        $records = $this->recordStore->getRecords();
        $entries = $records[\App\Listeners\Records\MostPointsInARegularSeason::BASE_KEY]['entries'];
        $this->assertEquals("[season=1] [playerId=".$this->jacquesAuger."] 4 Points.", $entries[0]);
    }


    public function test_multi_season()
    {
        $this->generateMultipleGamesForAGivenSeason(1, 2);
        $this->generateMultipleGamesForAGivenSeason(2, 1);

        $records = $this->recordStore->getRecords();
        $this->assertEquals(1, count($records[\App\Listeners\Records\MostPointsInARegularSeason::BASE_KEY]['entries']));
        $entries = $records[\App\Listeners\Records\MostPointsInARegularSeason::BASE_KEY]['entries'];
        $this->assertEquals("[season=1] [playerId=".$this->jacquesAuger."] 8 Points.", $entries[0]);
    }


    public function test_with_game_edit()
    {
        $this->generateMultipleGamesForAGivenSeason(1, 2);
        $gameId = $this->generateMultipleGamesForAGivenSeason(2, 1);

        $gameDate = '2016-07-27';
        $start = '9:00 AM';
        $end = '9:30 AM';
        $playoff = 0;
        $season = 2;


        $command = new \App\Commands\Game\EditFullGame(
            $gameId,
            $gameDate,
            $start,
            $end,
            $playoff,
            $season,
            1
        );


        $command->addWhiteGoalie($this->chrisLee);
        $command->addWhitePlayer($this->zachR);
        $command->addWhitePlayer($this->kevenB);
        $command->addWhitePlayer($this->ghislainD);
        $command->addWhitePlayer($this->paulE);
        $command->addWhitePlayer($this->paulG);


        $command->addBlackGoalie($this->davidR);
        $command->addBlackPlayer($this->chrisR);
        $command->addBlackPlayer($this->jeremieR);
        $command->addBlackPlayer($this->jacquesAuger);
        $command->addBlackPlayer($this->colinLemoine);


        $command->addWhitePoint(1, $this->ghislainD, $this->zachR);


        $command->addBlackPoint(1, $this->jeremieR, $this->jacquesAuger);
        $command->addBlackPoint(2, $this->jacquesAuger, '');
        $command->addBlackPoint(3, $this->jacquesAuger, '');
        $command->addBlackPoint(4, $this->jacquesAuger, '');
        $command->addBlackPoint(5, $this->jacquesAuger, '');
        $command->addBlackPoint(6, $this->jacquesAuger, '');
        $command->addBlackPoint(7, $this->jacquesAuger, '');
        $command->addBlackPoint(8, $this->jacquesAuger, '');
        $command->addBlackPoint(9, $this->jacquesAuger, '');
        $command->addBlackPoint(10, $this->jacquesAuger, '');
        $gameId = $this->dispatch($command);


        $records = $this->recordStore->getRecords();
        $this->assertEquals(1, count($records[\App\Listeners\Records\MostPointsInARegularSeason::BASE_KEY]['entries']));
        $entries = $records[\App\Listeners\Records\MostPointsInARegularSeason::BASE_KEY]['entries'];
        $this->assertEquals("[season=2] [playerId=".$this->jacquesAuger."] 10 Points.", $entries[0]);
    }



    private function generateMultipleGamesForAGivenSeason($seasonId = 1, $gameCount = 50, $playoffs = 0)
    {
        $gameDate = '2016-07-27';
        $start = '9:00 AM';
        $end = '9:30 AM';
        $playoff = $playoffs;
        $season = $seasonId;
        $gameId = '';

        for ($i = 1; $i <= $gameCount; $i++) {
            $command = new \App\Commands\Game\AddFullGame(
                $gameDate,
                $start,
                $end,
                $playoff,
                $season,
                $i
            );


            $command->addWhiteGoalie($this->chrisLee);
            $command->addWhitePlayer($this->zachR);
            $command->addWhitePlayer($this->kevenB);
            $command->addWhitePlayer($this->ghislainD);
            $command->addWhitePlayer($this->paulE);
            $command->addWhitePlayer($this->paulG);


            $command->addBlackGoalie($this->davidR);
            $command->addBlackPlayer($this->chrisR);
            $command->addBlackPlayer($this->jeremieR);
            $command->addBlackPlayer($this->jacquesAuger);
            $command->addBlackPlayer($this->colinLemoine);


            $command->addWhitePoint(1, $this->ghislainD, $this->zachR);


            $command->addBlackPoint(1, $this->jeremieR, $this->jacquesAuger);
            $command->addBlackPoint(2, $this->davidR, '');
            $command->addBlackPoint(3, $this->jacquesAuger, '');
            $command->addBlackPoint(4, $this->jeremieR, '');
            $command->addBlackPoint(5, $this->chrisR, '');
            $command->addBlackPoint(6, $this->chrisR, '');
            $command->addBlackPoint(7, $this->colinLemoine, '');
            $command->addBlackPoint(8, $this->chrisR, '');
            $command->addBlackPoint(9, $this->jacquesAuger, '');
            $command->addBlackPoint(10, $this->jacquesAuger, '');
            $gameId = $this->dispatch($command);

        }

        return $gameId;
    }




    private function genPlayerWithName($firstName, $lastName)
    {
        $email = 'email';
        $phoneNumber = 'phoneNumber';
        $height = 'height';
        $shoots = 'shoots';
        $favProPlayer = 'favProPlayer';
        $favProTeam = 'favProTeam';

        $command = new \App\Commands\Player\AddPlayer(
            $firstName,
            $lastName,
            $email,
            $phoneNumber,
            $height,
            $shoots,
            $favProPlayer,
            $favProTeam
        );
        $playerId = $this->dispatch($command);
        return $playerId;
    }
}
