<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        'vendor/laravel/framework/src/Illuminate/Redis/RedisServiceProvider.php',
        'vendor/laravel/framework/src/Illuminate/Redis/Database.php',
        'vendor/predis/predis/src/Client.php',
        'vendor/predis/predis/src/ClientInterface.php',
        'vendor/predis/predis/src/Configuration/Options.php',
        'vendor/predis/predis/src/Configuration/OptionsInterface.php',
        'vendor/predis/predis/src/Configuration/ConnectionFactoryOption.php',
        'vendor/predis/predis/src/Configuration/OptionInterface.php',
        'vendor/predis/predis/src/Connection/Factory.php',
        'vendor/predis/predis/src/Connection/FactoryInterface.php',
        'vendor/predis/predis/src/Connection/Parameters.php',
        'vendor/predis/predis/src/Connection/ParametersInterface.php',
        'vendor/predis/predis/src/Connection/StreamConnection.php',
        'vendor/predis/predis/src/Connection/ConnectionInterface.php',
        'vendor/predis/predis/src/Command/RawCommand.php',
        'vendor/predis/predis/src/Command/CommandInterface.php',
        'vendor/predis/predis/src/Configuration/ProfileOption.php',
        'vendor/predis/predis/src/Profile/Factory.php',
        'vendor/predis/predis/src/Profile/RedisVersion300.php',
        'vendor/predis/predis/src/Profile/ProfileInterface.php',
        'vendor/predis/predis/src/Command/StringGet.php',
        'vendor/predis/predis/src/Response/Status.php',
        'vendor/predis/predis/src/Response/ResponseInterface.php',
        'vendor/rcrowe/twigbridge/src/ServiceProvider.php',
        'vendor/rcrowe/twigbridge/src/Extension/Laravel/Str.php',
        'vendor/predis/predis/src/Command/HashGet.php',
        'vendor/predis/predis/src/Command/HashGetAll.php',
        'vendor/rcrowe/twigbridge/src/Engine/Twig.php',
        'vendor/rcrowe/twigbridge/src/Engine/Compiler.php',
        'vendor/rcrowe/twigbridge/src/Bridge.php',
        'vendor/twig/twig/lib/Twig/Environment.php',
        'vendor/twig/twig/lib/Twig/Loader/Chain.php',
        'vendor/twig/twig/lib/Twig/LoaderInterface.php',
        'vendor/twig/twig/lib/Twig/ExistsLoaderInterface.php',
        'vendor/twig/twig/lib/Twig/Loader/Array.php',
        'vendor/rcrowe/twigbridge/src/Twig/Loader.php',
        'vendor/twig/twig/lib/Twig/Cache/Filesystem.php',
        'vendor/twig/twig/lib/Twig/CacheInterface.php',
        'vendor/twig/twig/lib/Twig/Extension/Core.php',
        'vendor/twig/twig/lib/Twig/Extension/Escaper.php',
        'vendor/twig/twig/lib/Twig/Extension/Optimizer.php',
        'vendor/twig/twig/lib/Twig/Extension/Staging.php',
        'vendor/twig/twig/lib/Twig/Extension/Debug.php',
        'vendor/rcrowe/twigbridge/src/Extension/Loader/Facades.php',
        'vendor/twig/twig/lib/Twig/Extension/GlobalsInterface.php',
        'vendor/rcrowe/twigbridge/src/Extension/Loader/Filters.php',
        'vendor/rcrowe/twigbridge/src/Extension/Loader/Functions.php',
        'vendor/rcrowe/twigbridge/src/Extension/Laravel/Config.php',
        'vendor/rcrowe/twigbridge/src/Extension/Laravel/Dump.php',
        'vendor/rcrowe/twigbridge/src/Extension/Laravel/Input.php',
        'vendor/rcrowe/twigbridge/src/Extension/Laravel/Session.php',
        'vendor/rcrowe/twigbridge/src/Extension/Laravel/Translator.php',
        'vendor/rcrowe/twigbridge/src/Extension/Laravel/Url.php',
        'vendor/rcrowe/twigbridge/src/Twig/Template.php'
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        //
    ],

];
