# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.10.10"
  # Set virtual machine memory size
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.synced_folder "./../src/", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = ["./../chef","./other-cookbooks"]
    chef.add_recipe "shl-wpg"

    chef.json = {
      'shl-wpg' => {
        'domains' => '192.168.10.10',
        'secure' => false
      }
    }
  end

  config.vm.provision :shell, :path => "install.sh"
end